---
- name: install docker pip dependency
  pip:
    name: docker-py

- name: add docker GPG key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: get lsb_release codename
  command: lsb_release -cs
  register: lsb_release
  changed_when: no

- name: add docker apt repository
  apt_repository:
    repo: >
      deb [arch=amd64] https://download.docker.com/linux/debian
      {{lsb_release.stdout}}
      stable
  register: docker_apt

- name: update apt cache
  apt:
    update_cache: yes
  when: docker_apt.changed

- name: pin {{package}} version (apt)
  template:
    src: pin.j2
    dest: /etc/apt/preferences.d/{{package}}.pref
    owner: root
    group: root
    mode: "0644"

- name: install docker package
  apt:
    name: "{{package}}"
  notify: docker_restart
...
