---
version: "3"
services:
  forum:
    build:
      context: app/forum
      args:
        LOCAL_ENV: 1
    entrypoint: python3 manage.py runserver 0.0.0.0:5000
    volumes:
      - ./app/forum:/app
      - forum-media:/app/media
    environment:
      DEBUG: "True"
      LOCAL_ENV: "True"
      MINIO_ACCESS_KEY: KBP6WXGPS387090EZMG8
      MINIO_SECRET_KEY: DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A
    depends_on:
      - db
      - memcached
      - minio
    restart: always
  websocket:
    build: app/websocket
    volumes:
      - ./app/websocket:/app
  db:
    image: postgres:9.6-alpine
    volumes:
      - forum-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: crimson
    restart: always
  memcached:
    image: memcached:1.4-alpine
    restart: always
  minio:
    image: minio/minio
    command: server /export
    environment:
      MINIO_ACCESS_KEY: KBP6WXGPS387090EZMG8
      MINIO_SECRET_KEY: DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A
    volumes:
      - minio-storage:/export
    ports:
      - "9000:9000"
  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/forum/static:/data/static:ro
      - forum-media:/data/media:ro
    ports:
      - "8080:80"
    depends_on:
      - forum
      - websocket
    restart: always
volumes:
  forum-db: {}
  forum-media: {}
  minio-storage: {}
...
