---
version: "3.3"

services:

  forum:
    image: "{{forum_image}}:{{version}}"
    depends_on:
      - db
      - cache
    networks:
      - frontend
      - backend
    environment:
      DB_HOST: naxos_db
      CACHE_LOCATION: naxos_cache
      HOSTNAME: "{{inventory_hostname}}"
      DB_NAME: "{{db_name}}"
      DB_USER: "{{db_user}}"
      DB_PASSWORD: "{{db_password}}"
      AWS_STORAGE_BUCKET_NAME: "{{aws_storage_bucket_name}}"
      AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
      AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
      EMAIL_HOST: "{{email_host}}"
      EMAIL_PORT: "{{email_port}}"
      SERVER_EMAIL: "{{server_email}}"  # email address to use
      EMAIL_HOST_PASSWORD: "{{email_host_password}}"
      EMAIL_SERVER_PREFIX: "{{email_server_prefix}}"
      ADMIN_NAME: "{{admin_name}}"
      ADMIN_EMAIL: "{{admin_email}}"
    volumes:
      - "{{ansible_env.HOME}}/secrets:/app/secrets/"
      - "{{ansible_env.HOME}}/html:/app/templates/ads/:ro"

  websocket:
    image: "{{websocket_image}}:{{version}}"
    networks:
      - frontend

  db:
    image: postgres:{{postgres_version}}
    volumes:
      - forum-db:/var/lib/postgresql/data
    networks:
      - backend

  cache:
    image: memcached:{{memcached_version}}
    networks:
      - backend

  proxy:
    image: nginx:{{nginx_version}}
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      # - "80:80"
      # - "443:443"
    depends_on:
      - forum
      - websocket
    networks:
      - frontend
    volumes:
      - "{{nginx_folder}}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{nginx_folder}}/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "/usr/share/nginx/html:/usr/share/nginx/html:ro"  # ACME challenge

networks:
  frontend: {}
  backend: {}

volumes:
  forum-db: {}
  forum-media: {}
...
