---
- name: load vaulted variables
  include_vars: vars/vault.yml

# Snippets
- name: create host app folders
  file:
    state: directory
    path: "{{ansible_env.HOME}}/{{item}}"
  with_items:
    - html
    - secrets
- name: copy ad html snippets
  copy:
    src: "{{item}}"
    dest: "{{ansible_env.HOME}}/html/"
  with_items:
    - amazon.html
    - paypal_gift.html

# Swarm
- name: install docker-compose stack
  template:
    src: docker-compose.yml
    dest: /tmp
- name: launch swarm stack
  command: docker stack deploy --compose-file /tmp/docker-compose.yml {{project_name}}

# Purge expired sessions from db
- name: add clearsessions cron
  cron:
    name: django clearsessions
    job: docker exec forum python3 manage.py clearsessions
    hour: 4
    minute: 0
...
